### ISSUE TITLE
成员房间消息API

### ISSUE THREAD

**Issue by 1165115348** [theprimone/SNH48G-API#1]
首先感谢聚聚的分享 
另外想问一下 成员房间中的语音直播信息有相关的API吗？

**Comment by yunsii** [comment]
不好意思，才看到有个issue，成员房间消息有好多种情况，你也应该看到了。我觉得你是不是没看到成员直播API，里边就能获取直播和回放的相关信息。
```
liveType == 1  # 视频直播
liveType == 2  # 电台直播
```

**Comment by 1165115348** [comment]
> 
> 
> 不好意思，才看到有个issue，成员房间消息有好多种情况，你也应该看到了。我觉得你是不是没看到成员直播API，里边就能获取直播和回放的相关信息。
> 
> ```
> liveType == 1  # 视频直播
> liveType == 2  # 电台直播
> ```

不是这2个  还有一种是成员房间里的语音直播

**Comment by yunsii** [comment]
还有这种操作？我一直以为只有电台和视频直播两种啊。这个有单独的类似成员直播一样页面吗？没有的话，抓包也找不到API啊😂
 
实在不行的话可能只有监听房间消息了。
